objects/ActivateTriggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Activate Triggers</label>
</CustomObject>

objects/Contract_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Category</label>
        <referenceTo>Pricing_Category__c</referenceTo>
        <relationshipLabel>Contract Pricing</relationshipLabel>
        <relationshipName>Contract_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Contract Pricing</relationshipLabel>
        <relationshipName>Contract_Pricing</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Contract Pricing</label>
    <nameField>
        <label>Contract Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Email_Service_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings used for the email services</description>
    <fields>
        <fullName>NCR_Account_Id__c</fullName>
        <description>Id of the NCR Account to link the Work Order when an incoming email is received</description>
        <inlineHelpText>Id of the NCR Account to link the Work Order when an incoming email is received</inlineHelpText>
        <label>NCR Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Email Service Settings</label>
</CustomObject>

objects/Location_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Australia_Location_Id__c</fullName>
        <label>Australia Location Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Location Settings</label>
</CustomObject>

objects/Pricing_Category__c.object
<CustomObject>
    <label>Pricing Category</label>
    <nameField>
        <label>Pricing Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Part__c.object
<CustomObject>
    <description>Record triggers process builder and flows to create new product request with line items.</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Name to be requested</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Requested Parts</relationshipLabel>
        <relationshipName>Requested_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number to order</description>
        <label>Quantity Ordered</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Request Parts (Service Work Order)</relationshipLabel>
        <relationshipName>Request_Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Request Parts</relationshipLabel>
        <relationshipName>Request_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Part</label>
    <nameField>
        <displayFormat>RPN-{00000}</displayFormat>
        <label>Request Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Part__c.object
<CustomObject>
    <description>Custom object to allow global action on a Service automating insertion of Product Consumed or Products Required</description>
    <fields>
        <fullName>Product_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Item from Van Stock</description>
        <label>Product Item</label>
        <referenceTo>ProductItem</referenceTo>
        <relationshipLabel>Service_Parts</relationshipLabel>
        <relationshipName>Service_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product_Item__r.Product2.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Consumed__c</fullName>
        <label>Quantity Consumed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Work_Order_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service Parts (Service Work Order)</relationshipLabel>
        <relationshipName>Service_Parts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service_Parts</relationshipLabel>
        <relationshipName>Service_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Part</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Service Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceAppointment.object
<CustomObject>
    <fields>
        <fullName>Invoice_Created__c</fullName>
        <formula>Work_Order__r.WOService_Invoice_Created__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Service Appointments</relationshipLabel>
        <relationshipName>Service_Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Usage_FSL__c.object
<CustomObject>
    <description>BEST TS Usage for Field Service Lightning</description>
    <fields>
        <fullName>Contract_Pricing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Pricing</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract_Pricing__c.Service_Contract__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Contract__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract_Pricing__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Created__c</fullName>
        <formula>Work_Order__r.Invoice_Created__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pricing_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Category</label>
        <referenceTo>Pricing_Category__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Contract__c</fullName>
        <label>Service Contract</label>
        <referenceTo>ServiceContract</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <label>Work Order</label>
        <referenceTo>WorkOrder</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Invoice_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Created</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestUtility.cls
public class TestUtility {

    public static List<Account> createAccounts(Integer count) {

        List<Account> accountList = new List<Account>();
        for(Integer i=0; i<count; i++){
            accountList.add(new Account(Name= 'TestBestTS'+i, Type = 'Client', BillingCity = 'Sydney', BillingCountry = 'Australia'));
        }
        return accountList;
    }

    public static List<WorkOrder> createWorkOrders(Account account, String recordTypeName, Integer count) {
        Map<String,Schema.RecordTypeInfo> rtMap = RecordTypeDAO.getRecordTypes(Schema.SObjectType.WorkOrder);
        Id woRecordTypeId = rtMap.get(recordTypeName).getRecordTypeId();
        List<WorkOrder> woList = new List<WorkOrder>();
        for(Integer i=0; i<count; i++){
            woList.add(new WorkOrder(RecordTypeId =woRecordTypeId,
                                     AccountId = account.Id, 
                                     Status = 'New', 
                                     Invoice_Created__c = false));
        }
        return woList;
    }

    public static List<WorkOrder> createChildWorkOrders(Account account, WorkOrder parentWorkOrder, String recordTypeName, Integer count) {
        Map<String,Schema.RecordTypeInfo> rtMap = RecordTypeDAO.getRecordTypes(Schema.SObjectType.WorkOrder);
        Id woRecordTypeId = rtMap.get(recordTypeName).getRecordTypeId();
        List<WorkOrder> woList = new List<WorkOrder>();
        for(Integer i=0; i<count; i++){
            woList.add(new WorkOrder(RecordTypeId =woRecordTypeId,
                                     AccountId = account.Id, 
                                     Status = 'New', 
                                     Invoice_Created__c = false,
                                     ParentWorkOrderId = parentWorkOrder.Id));
        }
        return woList;
    }

    public static List<ServiceAppointment> createServiceAppointments(Set<Id> parentRecordIds, Integer nbServiceAppointments){
        List<ServiceAppointment> serviceAppointments = new List<ServiceAppointment>();
        for(Id parentRecordId : parentRecordIds){
            for(Integer i=0; i<nbServiceAppointments; i++){
                serviceAppointments.add(new ServiceAppointment( ParentRecordId = parentRecordId,
                                                                //Status=Constants.SERVICE_APPOINTMENT_STATUS_NEW,
                                                                DueDate = Datetime.now().addDays(10),
                                                                EarliestStartTime = Datetime.now(),
                                                                SchedStartTime = Datetime.now(),
                                                                SchedEndTime = Datetime.now().addHours(1),
                                                                Duration = 60,
                                                                DurationType=Constants.SERVICE_APPOINTMENT_DURATION_TYPE_MINUTES));
            }
        }
        return serviceAppointments;
    }

    public static List<User> createCommunityUserTechnicians(Integer count){
        Profile techProfile = [Select Id From Profile Where Name LIKE :Constants.PROFILE_NAME_FOR_COMMUNITY_TECHNICIAN];
        return createCommunityUsers(count, techProfile.Id);
    }

    public static List<User> createCommunityUsers(Integer count, Id profileId){
        User sysAdmin = [SELECT Id FROM User WHERE Profile.Name='System Administrator' AND UserRoleId != null AND IsActive = true LIMIT 1][0];
        List<User> users = new List<User>();
        System.runAs(sysAdmin){
            Account bestAccount = new Account(Name='Best');
            insert bestAccount;

            List<Contact> contacts = new List<Contact>();

            for(Integer i=0; i<count; i++){
                contacts.add(new Contact(FirstName='Test',
                                        LastName='Test Last Name',
                                        AccountId = bestAccount.Id));
            }
            insert contacts;

            UserRole communityRole = [Select Id From UserRole Where PortalType = 'CustomerPortal' Limit 1][0];
            Integer i=0;
            for(Contact contact : contacts){
                users.add(new User(   ProfileId = profileId, 
                                        USERNAME = 'sfuser'+i+'@proquestit.com', 
                                        LASTNAME = 'Test', 
                                        FIRSTNAME = 'Test', 
                                        EMAIL = 'noreply@chatter.salesforce.com', 
                                        EMAILPREFERENCESAUTOBCC = true, 
                                        EMAILPREFERENCESAUTOBCCSTAYINTOUCH = false, 
                                        EMAILPREFERENCESSTAYINTOUCHREMINDER = true, 
                                        ALIAS = 'sfuser'+i, 
                                        COMMUNITYNICKNAME = 'sfuser'+i, 
                                        ISACTIVE = true, 
                                        TIMEZONESIDKEY = 'Australia/Sydney', 
                                        LOCALESIDKEY = 'en_AU', 
                                        LANGUAGELOCALEKEY = 'en_US', 
                                        EMAILENCODINGKEY = 'ISO-8859-1',
                                        ContactId=contact.Id));
                i++;
            }
            insert users;
        }
        return users;
    }

    public static List<User> createUsers(Integer count, Id profileId){
        List<User> entries = new List<User>();
        for(Integer i=0; i<count; i++){
            entries.add(new User(   ProfileId = profileId, 
                                    USERNAME = 'sfuser'+i+'@proquestit.com', 
                                    LASTNAME = 'Test', 
                                    FIRSTNAME = 'Test', 
                                    EMAIL = 'noreply@chatter.salesforce.com', 
                                    EMAILPREFERENCESAUTOBCC = true, 
                                    EMAILPREFERENCESAUTOBCCSTAYINTOUCH = false, 
                                    EMAILPREFERENCESSTAYINTOUCHREMINDER = true, 
                                    ALIAS = 'sfuser'+i, 
                                    COMMUNITYNICKNAME = 'sfuser'+i, 
                                    ISACTIVE = true, 
                                    TIMEZONESIDKEY = 'Australia/Sydney', 
                                    LOCALESIDKEY = 'en_AU', 
                                    LANGUAGELOCALEKEY = 'en_US', 
                                    EMAILENCODINGKEY = 'ISO-8859-1' ));
        }
        return entries;
    }

    public static List<ServiceResource> createServiceResources(List<User> users, String serviceResourceType){
        List<ServiceResource> serviceResources = new List<ServiceResource>();
        for(User user : users){
            serviceResources.add(new ServiceResource(Name = user.FirstName + ' ' + user.LastName,
                                                    IsActive = true,
                                                    ResourceType = serviceResourceType,
                                                    RelatedRecordId = user.Id));
        }
        return serviceResources;
    }

    public static void assignServiceResourcesToServiceTerritory(List<ServiceResource> serviceResources, ServiceTerritory territory){
        Map<Id,ServiceResource> serviceResourcesById = new Map<Id,ServiceResource>(serviceResources);
        List<ServiceTerritoryMember> stms = [SELECT Id,ServiceResourceId, ServiceTerritoryId, TerritoryType, EffectiveStartDate, EffectiveEndDate FROM ServiceTerritoryMember WHERE ServiceResourceId IN :serviceResourcesById.keySet() AND TerritoryType='P' AND EffectiveStartDate<=:DateTime.Now() AND (EffectiveEndDate=null OR EffectiveEndDate >=:DateTime.Now())];
        if(territory == null){
            territory = createServiceTerritories(1)[0];
        }

        List<ServiceTerritoryMember> stmsToInsert = new List<ServiceTerritoryMember>();
        for(ServiceResource sr : serviceResources){
            Boolean hasPrimaryServiceTerritory = false;
            for(ServiceTerritoryMember stm : stms){
                if(sr.Id == stm.ServiceResourceId){
                    hasPrimaryServiceTerritory=true;
                    break;
                }
            }
            if(!hasPrimaryServiceTerritory){
                stmsToInsert.add(new ServiceTerritoryMember(ServiceResourceId=sr.Id, ServiceTerritoryId=territory.Id, TerritoryType='P',EffectiveStartDate=Date.Today().addDays(-1), EffectiveEndDate=Date.Today().addDays(1)));
            }
        }
        if(stmsToInsert.size()>0){
            insert stmsToInsert;
        }
    }

    public static List<ServiceContract> createServiceContracts(Account account, Integer count) {

        List<ServiceContract> contractsList = new List<ServiceContract>();
        for(Integer i=0; i<count; i++){
            contractsList.add(new ServiceContract(AccountId = account.Id, Name = 'Test Service Contract ' + i));
        }
        return contractsList;
    }


    // create pricing category
    public static List<Pricing_Category__c> createPricingCategory(Account account, Integer count) {

        List<Pricing_Category__c> pricingCategoriesList = new List<Pricing_Category__c>();
        for(Integer i=0; i<count; i++){
            pricingCategoriesList.add(new Pricing_Category__c(Name = 'Test Pricing Category ' + i));
        }
        return pricingCategoriesList;
    }

    // create contract pricing
    public static List<Contract_Pricing__c> createContractPricing(Id recTypeId, ServiceContract serviceContract, Pricing_Category__c pricingCategory, Integer count) {

        List<Contract_Pricing__c> contractPricingList = new List<Contract_Pricing__c>();
        for(Integer i=0; i<count; i++){
            contractPricingList.add(new Contract_Pricing__c(Name = 'Test contract pricing ' + i, 
                                                            RecordTypeId = recTypeId,
                                                            Service_Contract__c = serviceContract.Id,
                                                            Pricing_Category__c = pricingCategory.Id));
        }
        return contractPricingList;
    }

    //Create the custom settings Email Service Settings
    public static void createEmailServiceSettingsCS(Id accountId){
        Email_Service_Settings__c emailServiceSettingsCS = Email_Service_Settings__c.getOrgDefaults();
        emailServiceSettingsCS.SetupOwnerId=UserInfo.getOrganizationId();
        emailServiceSettingsCS.NCR_Account_Id__c = accountId;
        upsert emailServiceSettingsCS;
    }

    public static void createLocationSettingsCS(){
        OperatingHours opHours = new OperatingHours(Name='Operating Hours', TimeZone='Australia/Sydney');
        insert opHours;

        ServiceTerritory location = new ServiceTerritory(Name = 'Test Location', 
                                                         OperatingHoursId = opHours.Id,
                                                         IsActive=true);
        insert location;

        Location_Settings__c locationSettingsCS = Location_Settings__c.getOrgDefaults();
        locationSettingsCS.Australia_Location_Id__c = location.Id;
        upsert locationSettingsCS;
    }

    public static void createActivateTriggerCS(){
        ActivateTriggers__c activateTriggerCS = ActivateTriggers__c.getOrgDefaults();
        activateTriggerCS.Enabled__c = true;
        upsert activateTriggerCS;       
    }

    public static List<ServiceTerritory> createServiceTerritories(Integer nbServiceTerritory){
        OperatingHours opHours = new OperatingHours(Name='Operating Hours', TimeZone='Australia/Sydney');
        insert opHours;

        List<ServiceTerritory> territories = new List<ServiceTerritory>();
        for(Integer i=0; i<nbServiceTerritory; i++){
            ServiceTerritory territory = new ServiceTerritory(Name = 'Test Service Territory '+i, 
                                                             OperatingHoursId = opHours.Id,
                                                             IsActive=true);
            territories.add(territory);
        }
        insert territories;
        return territories;
    }

    public static List<Usage_FSL__c> createUsages(Id recTypeId, WorkOrder parentWorkorder, ServiceContract serviceContract, Contract_Pricing__c contractPricing, WorkOrder childWorkOrder, Integer count) {

        List<Usage_FSL__c> usages = new List<Usage_FSL__c>();
        for(Integer i=0; i<count; i++){
            usages.add(new Usage_FSL__c(RecordTypeId = recTypeId,
                                        Work_Order__c = parentWorkorder.Id,
                                        Service_Contract__c = serviceContract.Id,
                                        Contract_Pricing__c = contractPricing.Id,
                                        Service_Work_Order__c = childWorkOrder.Id));
        }
        return usages;
    }

    public static List<WorkType> createWorkTypes(Integer count) {
        List<WorkType> workTypes = new List<WorkType>();
        for(Integer i=0; i<count; i++){
            workTypes.add(new WorkType(Name = 'Test Work Type', 
                                        EstimatedDuration = 60.00, 
                                        DurationType='Minutes'));
        }
        return workTypes;
    }

    //Return list of ProductItems of a Van given length of number of products to create
    public static List<ProductItem> createNewProductItems(integer len){
        List<Product2> prodList = new list<Product2>();
        for(integer i=0;i<len;i++){
            prodList.add(new Product2(Name='Product-'+i,ProductCode='Code-'+i,Description='Description-'+i,IsActive=true,QuantityUnitOfMeasure='Each'));
        }
        insert prodList;

        Schema.Location van = new Schema.Location(Name='Van', LocationType='Van',IsInventoryLocation=true,isMobile=true);
        insert van;

        List<ProductItem> items = new List<ProductItem>();
        for(Product2 p : prodList){
            ProductItem pi = new ProductItem(Product2Id=p.Id, LocationId=van.Id, QuantityUnitOfMeasure=p.QuantityUnitOfMeasure,QuantityOnHand=10);
            items.add(pi);
        }
        return items;
    }

    //Return list of Service Parts for a Service Work Order
    public static List<Service_Part__c> createNewServiceParts(WorkOrder woService, List<ProductItem> productList){
        List<Service_Part__c> spList = new List<Service_Part__c>();
        for(ProductItem pit:productList){
            Service_Part__c sp = new Service_Part__c(Work_Order_Service__c=woService.Id,Product_Item__c=pit.Id,Quantity_Consumed__c=1);
            spList.add(sp);
        }

        return spList;
    }

    //public retunr list of Request_Part__c for a Service Work Order
    public static List<Request_Part__c> createNewPartRequest(WorkOrder woService, List<ProductItem> productList){
        List<Request_Part__c> partsList = new List<Request_Part__c>();
        for(ProductItem pit:productList){
            Request_Part__c part = new Request_Part__c(Work_Order_Service__c=woService.Id,Product_Name__c=pit.Product2Id,Quantity__c=5);
            partsList.add(part);
        }

        return partsList;
    }
}