objects/ActivateTriggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Activate Triggers</label>
</CustomObject>

objects/Email_Parsing_Field_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Email_Field__c</fullName>
        <description>Name of the field in the Email</description>
        <inlineHelpText>Name of the field in the Email</inlineHelpText>
        <label>Email Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Field_Type__c</fullName>
        <description>Field Type of the Salesforce Field</description>
        <inlineHelpText>Field Type of the Salesforce Field</inlineHelpText>
        <label>SF Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SF_Field__c</fullName>
        <description>API Name of the Salesforce Field</description>
        <inlineHelpText>API Name of the Salesforce Field</inlineHelpText>
        <label>SF Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Object_Type__c</fullName>
        <description>API Name of the Salesforce objects</description>
        <inlineHelpText>API Name of the Salesforce objects</inlineHelpText>
        <label>SF Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WorkOrder</fullName>
                </value>
                <value>
                    <fullName>CKSW_BASE__Service__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Parsing Field Mapping</label>
    <pluralLabel>Email Parsing Field Mappings</pluralLabel>
</CustomObject>

objects/Licensing__mdt.object
<CustomObject>
    <fields>
        <fullName>Total_Number_of_Licenses__c</fullName>
        <label>Total Number of Licenses</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Licensing</label>
    <pluralLabel>Licensing</pluralLabel>
</CustomObject>

objects/Month_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Month_Digit__c</fullName>
        <label>Month Digit</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Text__c</fullName>
        <label>Month Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Month Mapping</label>
    <pluralLabel>Month Mapping</pluralLabel>
</CustomObject>

objects/Technician_Status_Transition__mdt.object
<CustomObject>
    <fields>
        <fullName>From_Status_API_Name__c</fullName>
        <label>From Status API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Travel Start</fullName>
                </value>
                <value>
                    <fullName>Capture Signature</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Travel End</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>From_Status__c</fullName>
        <label>From Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Travel Start</fullName>
                </value>
                <value>
                    <fullName>Travel End</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Capture Signature</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Status_API_Name__c</fullName>
        <label>To Status API Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Travel Start</fullName>
                </value>
                <value>
                    <fullName>Capture Signature</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Travel End</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Status__c</fullName>
        <label>To Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Travel Start</fullName>
                </value>
                <value>
                    <fullName>Travel End</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Capture Signature</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Technician Status Transition</label>
    <pluralLabel>Technician Status Transitions</pluralLabel>
</CustomObject>

classes/CustomMetadataTypeDAO.cls
public with sharing class CustomMetadataTypeDAO {
	public static List<Licensing__mdt> getLicensingForProfile(String profileName){
		return [Select  Total_Number_of_Licenses__c
				From	Licensing__mdt
				Where 	MasterLabel = :profileName];
	}

    public static List<Email_Parsing_Field_Mapping__mdt> getEmailParsingMapping(){
        return [SELECT Email_Field__c, SF_Field__c, SF_Field_Type__c, SF_Object_Type__c
                FROM Email_Parsing_Field_Mapping__mdt];
    }

    public static List<Month_Mapping__mdt> getMonthMappingByMonthText(List<String> monthTexts){
        return [SELECT Month_Digit__c, Month_Text__c
                FROM Month_Mapping__mdt 
                WHERE Month_Text__c IN :monthTexts];
    }

    public static List<Technician_Status_Transition__mdt> getTechnStatusTransitionByFromStatusAPI(List<String> fromStatus){
        return [SELECT From_Status__c, From_Status_API_Name__c, To_Status__c, To_Status_API_Name__c
                FROM Technician_Status_Transition__mdt 
                WHERE From_Status_API_Name__c IN :fromStatus];
    }
    
    
    public static boolean getTriggerSettingForFSLMigration(){
        boolean enabled = true;
        if(Test.isRunningTest()){
            return enabled;
        }
       
        ActivateTriggers__c trigSetting = ActivateTriggers__c.getOrgDefaults();
      
       
        if(trigSetting!=null  && trigSetting.Enabled__c == false) {
           enabled = false;
        }
        return enabled;        
   }
}