objects/CKSW_BASE__Service__c.object
<CustomObject>
</CustomObject>

objects/Contract_Pricing__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Category</label>
        <referenceTo>Pricing_Category__c</referenceTo>
        <relationshipLabel>Contract Pricing</relationshipLabel>
        <relationshipName>Contract_Pricing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contract Pricing</label>
    <nameField>
        <label>Contract Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Category__c.object
<CustomObject>
    <label>Pricing Category</label>
    <nameField>
        <label>Pricing Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Usage_FSL__c.object
<CustomObject>
    <description>BEST TS Usage for Field Service Lightning</description>
    <fields>
        <fullName>Contract_Pricing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Pricing</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contract_Pricing__c.Service_Contract__c</field>
                <operation>equals</operation>
                <valueField>$Source.Service_Contract__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract_Pricing__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Created__c</fullName>
        <formula>Work_Order__r.Invoice_Created__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pricing_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Category</label>
        <referenceTo>Pricing_Category__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Engineering_Cost__c</fullName>
        <label>Total Engineering Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Engineering_Revenue__c</fullName>
        <label>Total Engineering Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Pass_Through_Cost__c</fullName>
        <label>Total Pass Through Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Pass_Through_Revenue__c</fullName>
        <label>Total Pass Through Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>Invoice_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Engineering_Cost__c</fullName>
        <label>Service Engineering Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Engineering_Revenue__c</fullName>
        <label>Service Engineering Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Pass_Through_Cost__c</fullName>
        <label>Service Pass Through Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Pass_Through_Revenue__c</fullName>
        <label>Service Pass Through Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UsageFSLHandlerTest.cls
@isTest
public class UsageFSLHandlerTest {

    static testMethod void testRollupCalculations() {

        List<Account> accounts = TestUtility.createAccounts(2);
        insert accounts;

        List<CKSW_BASE__Service_Type__c> serviceTypes = TestUtility.createServiceTypes(2);
        insert serviceTypes;

        List<WorkOrder> workorders = TestUtility.createWorkOrders(accounts.get(0), 2);
        insert workorders;

        List<CKSW_BASE__Location__c> locations = TestUtility.createLocations(accounts.get(0), 2);
        insert locations;

        List<CKSW_BASE__Service__c> services = TestUtility.createServices(workorders.get(0), serviceTypes.get(0), locations.get(0), Constants.SERVICE_STATUS_IN_PROGRESS, 2);
        insert services;

        List<ServiceContract> servicecontracts = TestUtility.createServiceContracts(accounts.get(0), 2);
        insert servicecontracts;

        List<Pricing_Category__c> pricingCategories = TestUtility.createPricingCategory(accounts.get(0), 2);
        insert pricingCategories;

        Map<String,Schema.RecordTypeInfo> rtMap = RecordTypeDAO.getRecordTypes(Schema.SObjectType.Contract_Pricing__c);
        Id pricingCategoryRT = rtMap.get(Constants.CONTRACT_PRICING_RECORD_TYPE_MARKUP_BASED).getRecordTypeId(); 

        List<Contract_Pricing__c> contractPricings = TestUtility.createContractPricing(pricingCategoryRT, servicecontracts.get(0), pricingCategories.get(0), 2);
        insert contractPricings;

        rtMap = RecordTypeDAO.getRecordTypes(Schema.SObjectType.Usage_FSL__c);
        Id usageRT = rtMap.get(Constants.USAGE_RECORD_TYPE_STANDARD_USAGE).getRecordTypeId(); 

        Test.startTest();
            List<Usage_FSL__c> usages = TestUtility.createUsages(usageRT, workorders.get(0), servicecontracts.get(0), contractPricings.get(0), services.get(0), 2);
            usages.get(0).Total_Engineering_Cost__c = 10.00;
            usages.get(0).Total_Engineering_Revenue__c = 100.00;
            usages.get(0).Total_Pass_Through_Cost__c = 40.00;
            usages.get(0).Total_Pass_Through_Revenue__c = 400.00;


            usages.get(1).Total_Engineering_Cost__c = 30.00;
            usages.get(1).Total_Engineering_Revenue__c = 400.00;
            usages.get(1).Total_Pass_Through_Cost__c = 10.00;
            usages.get(1).Total_Pass_Through_Revenue__c = 100.00;

            insert usages;
        
        Test.stopTest();
        
        List<CKSW_BASE__Service__c> updatedservices = [SELECT Service_Engineering_Cost__c, Service_Engineering_Revenue__c, 
                                                                Service_Pass_Through_Cost__c, Service_Pass_Through_Revenue__c 
                                                       FROM CKSW_BASE__Service__c 
                                                       WHERE Id =: services.get(0).Id];
        System.assert(updatedservices.size() > 0);                                                
        System.assertEquals(40.00, updatedservices.get(0).Service_Engineering_Cost__c);
        System.assertEquals(500.00, updatedservices.get(0).Service_Engineering_Revenue__c);
        System.assertEquals(50.00, updatedservices.get(0).Service_Pass_Through_Cost__c);
        System.assertEquals(500.00, updatedservices.get(0).Service_Pass_Through_Revenue__c);
        
       
    }
    
    static testMethod void testUsageDelete() {

        List<Account> accounts = TestUtility.createAccounts(2);
        insert accounts;

        List<CKSW_BASE__Service_Type__c> serviceTypes = TestUtility.createServiceTypes(2);
        insert serviceTypes;

        List<WorkOrder> workorders = TestUtility.createWorkOrders(accounts.get(0), 2);
        insert workorders;

        List<CKSW_BASE__Location__c> locations = TestUtility.createLocations(accounts.get(0), 2);
        insert locations;

        List<CKSW_BASE__Service__c> services = TestUtility.createServices(workorders.get(0), serviceTypes.get(0), locations.get(0), Constants.SERVICE_STATUS_IN_PROGRESS, 2);
        insert services;

        List<ServiceContract> servicecontracts = TestUtility.createServiceContracts(accounts.get(0), 2);
        insert servicecontracts;

        List<Pricing_Category__c> pricingCategories = TestUtility.createPricingCategory(accounts.get(0), 2);
        insert pricingCategories;

        Map<String,Schema.RecordTypeInfo> rtMap = RecordTypeDAO.getRecordTypes(Schema.SObjectType.Contract_Pricing__c);
        Id pricingCategoryRT = rtMap.get(Constants.CONTRACT_PRICING_RECORD_TYPE_MARKUP_BASED).getRecordTypeId(); 

        List<Contract_Pricing__c> contractPricings = TestUtility.createContractPricing(pricingCategoryRT, servicecontracts.get(0), pricingCategories.get(0), 2);
        insert contractPricings;

        rtMap = RecordTypeDAO.getRecordTypes(Schema.SObjectType.Usage_FSL__c);
        Id usageRT = rtMap.get(Constants.USAGE_RECORD_TYPE_STANDARD_USAGE).getRecordTypeId(); 
        
        List<Usage_FSL__c> usages = TestUtility.createUsages(usageRT, workorders.get(0), servicecontracts.get(0), contractPricings.get(0), services.get(0), 2);
        usages.get(0).Total_Engineering_Cost__c = 10.00;
        usages.get(0).Total_Engineering_Revenue__c = 100.00;
        usages.get(0).Total_Pass_Through_Cost__c = 40.00;
        usages.get(0).Total_Pass_Through_Revenue__c = 400.00;

        insert usages;
        
        List<WorkOrder> newworkorders = [SELECT Id, Invoice_Created__c FROM WorkOrder WHERE Id =: workorders.get(0).Id];
        newworkorders.get(0).Status = 'Closed';
        newworkorders.get(0).Invoice_Created__c = true;
        update newworkorders.get(0);
        
        Test.startTest();
            try{
                delete usages.get(0);
            } catch(Exception exp) {
                System.assert(exp.getMessage().contains(Label.CannotDeleteUsage));
            }
            
        Test.stopTest();
    }
}