objects/CKSW_BASE__Service__c.object
<CustomObject>
</CustomObject>

objects/Email_Log__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Log</label>
    <nameField>
        <displayFormat>EMAILLOG-{000000000}</displayFormat>
        <label>Email Log No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Email_Parsing_Field_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Email_Field__c</fullName>
        <description>Name of the field in the Email</description>
        <inlineHelpText>Name of the field in the Email</inlineHelpText>
        <label>Email Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Field_Type__c</fullName>
        <description>Field Type of the Salesforce Field</description>
        <inlineHelpText>Field Type of the Salesforce Field</inlineHelpText>
        <label>SF Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>DateTime</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
                <value>
                    <fullName>Decimal</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SF_Field__c</fullName>
        <description>API Name of the Salesforce Field</description>
        <inlineHelpText>API Name of the Salesforce Field</inlineHelpText>
        <label>SF Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Object_Type__c</fullName>
        <description>API Name of the Salesforce objects</description>
        <inlineHelpText>API Name of the Salesforce objects</inlineHelpText>
        <label>SF Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>WorkOrder</fullName>
                </value>
                <value>
                    <fullName>CKSW_BASE__Service__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Email Parsing Field Mapping</label>
    <pluralLabel>Email Parsing Field Mappings</pluralLabel>
</CustomObject>

objects/Territory_Contract_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To map a territory with a contract Id</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Territory Contract Mapping</label>
</CustomObject>

classes/NCRIncomingEmailHandlerTest.cls
@isTest
public class NCRIncomingEmailHandlerTest {

    @testSetup static void testDataSetup(){
        Account account = TestUtility.createAccounts(1)[0];
        insert account;
        TestUtility.createEmailServiceSettingsCS(account.Id);

        List<ServiceContract> serviceContracts = TestUtility.createServiceContracts(account,2);
        insert serviceContracts;

        ServiceContract serviceContract = [SELECT ContractNumber FROM ServiceContract WHERE Id = :serviceContracts[0].Id];

        Territory_Contract_Mapping__c territoryMapping = new Territory_Contract_Mapping__c();
        territoryMapping.Name = 'TerritoryName';
        territoryMapping.Contract_Number__c = String.valueOf(serviceContract.ContractNumber);
        insert territoryMapping;

        TestUtility.createLocationSettingsCS();
    }
    
    @isTest
	static void testHandleInboundEmailSuccess() {

        // Create a new email and envelope object
        Messaging.InboundEmail email  = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        // Create the email body
        Integer i = 0;
        List<Email_Parsing_Field_Mapping__mdt> fieldMapping = [SELECT Email_Field__c, SF_Field__c, SF_Field_Type__c, SF_Object_Type__c
                                                                        FROM Email_Parsing_Field_Mapping__mdt WHERE SF_Object_Type__c = 'WorkOrder'];
        email.htmlBody = '<html><body>';
        email.htmlBody += '<tr><td>Attribute Name</td><td>Attribute Value</td></tr>';
        for(Email_Parsing_Field_Mapping__mdt mapping : fieldMapping){
            if(mapping.SF_Field_Type__c == 'DateTime'){
                email.htmlBody += '<tr><td>' + mapping.Email_Field__c + '</td><td>19-JUL-2017 08:06</td></tr>';
            }
            else if(mapping.SF_Field_Type__c == 'Text'){
                email.htmlBody += '<tr><td>' + mapping.Email_Field__c + '</td><td>test' + i + '</td></tr>';
            }
            i++;
        }
        email.htmlBody += '<tr><td>Territory</td><td>TerritoryName</td></tr>';
        email.htmlBody += '<tr><td>Equipment Address3</td><td>SYDNEY NSW AU 2000</td></tr>';
        email.htmlBody += '</body></html>';

        email.fromAddress ='test@test.com';
        String contactEmail = 'john@test.com';
        email.ccAddresses = new String[] {' John Test <' + contactEmail + '>'};
        email.subject = 'Email-Test-SR:123456789-Test';
        
        NCRIncomingEmailHandler emailHandler = new NCRIncomingEmailHandler();
        
        Test.startTest();
        Messaging.InboundEmailResult result = emailHandler.handleInboundEmail(email, env);
        Test.stopTest();
        
        System.assert(result.success, 'InboundEmailResult returned a failure message');
        List<WorkOrder> workOrders = [SELECT Id FROM WorkOrder];
        System.assertEquals(1,workOrders.size(),'Work Order not created as expected');

        List<CKSW_BASE__Service__c> services = [SELECT Id FROM CKSW_BASE__Service__c];
        System.assertEquals(1,services.size(),'Service not created as expected');
	}

    @isTest
    static void testhandleInboundEmailNoContractMapping() {

        // Create a new email and envelope object
        Messaging.InboundEmail email  = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        // Create the email body
        Integer i = 0;
        List<Email_Parsing_Field_Mapping__mdt> fieldMapping = [SELECT Email_Field__c, SF_Field__c, SF_Field_Type__c, SF_Object_Type__c
                                                                        FROM Email_Parsing_Field_Mapping__mdt WHERE SF_Object_Type__c = 'WorkOrder'];
        email.htmlBody = '<html><body>';
        email.htmlBody += '<tr><td>Attribute Name</td><td>Attribute Value</td></tr>';
        for(Email_Parsing_Field_Mapping__mdt mapping : fieldMapping){
            if(mapping.SF_Field_Type__c == 'DateTime'){
                email.htmlBody += '<tr><td>' + mapping.Email_Field__c + '</td><td>19-JUL-2017 08:06</td></tr>';
            }
            else if(mapping.SF_Field_Type__c == 'Text'){
                email.htmlBody += '<tr><td>' + mapping.Email_Field__c + '</td><td>test' + i + '</td></tr>';
            }
            i++;
        }
        email.htmlBody += '</body></html>';

        email.fromAddress ='test@test.com';
        String contactEmail = 'john@test.com';
        email.ccAddresses = new String[] {' John Test <' + contactEmail + '>'};
        email.subject = 'Email-Test-SR:123456789-Test';
        
        NCRIncomingEmailHandler emailHandler = new NCRIncomingEmailHandler();
        
        Test.startTest();
        Messaging.InboundEmailResult result = emailHandler.handleInboundEmail(email, env);
        Test.stopTest();
        
        System.assert(result.success, 'InboundEmailResult returned a failure message');

        List<Email_Log__c> emailLogs = [SELECT Id, Status__c FROM Email_Log__c];
        System.assertEquals(1,emailLogs.size(),'Email Log not created as expected');
        System.assertEquals('Error',emailLogs[0].Status__c,'Email Log not create with the right status');
    }

    @isTest
    static void testhandleInboundEmailError() {

        // Create a new email and envelope object
        Messaging.InboundEmail email  = new Messaging.InboundEmail();
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();

        // Create the email body
        Integer i = 0;
        List<Email_Parsing_Field_Mapping__mdt> fieldMapping = [SELECT Email_Field__c, SF_Field__c, SF_Field_Type__c, SF_Object_Type__c
                                                                        FROM Email_Parsing_Field_Mapping__mdt WHERE SF_Object_Type__c = 'WorkOrder'];
        email.htmlBody = '<html><body>';
        email.htmlBody += '<tr><td>Attribute Name</td><td>Attribute Value</td></tr>';
        for(Email_Parsing_Field_Mapping__mdt mapping : fieldMapping){
            if(mapping.SF_Field_Type__c == 'DateTime'){
                email.htmlBody += '<tr><td>' + mapping.Email_Field__c + '</td><td>19-JUL-2017 08:06</td></tr>';
            }
            else if(mapping.SF_Field_Type__c == 'Text'){
                email.htmlBody += '<tr><td>' + mapping.Email_Field__c + '</td><td>Test value too long for some fields' + i + '</td></tr>';
            }
            i++;
        }
        email.htmlBody += '<tr><td>Territory</td><td>TerritoryName</td></tr>';
        email.htmlBody += '</body></html>';

        email.fromAddress ='test@test.com';
        String contactEmail = 'john@test.com';
        email.ccAddresses = new String[] {' John Test <' + contactEmail + '>'};
        email.subject = 'Email-Test-SR:123456789-Test';
        
        NCRIncomingEmailHandler emailHandler = new NCRIncomingEmailHandler();
        
        Test.startTest();
        Messaging.InboundEmailResult result = emailHandler.handleInboundEmail(email, env);
        Test.stopTest();
        
        System.assert (!result.success, 'InboundEmailResult should have returned a failure message');

        List<Email_Log__c> emailLogs = [SELECT Id, Status__c FROM Email_Log__c];
        System.assertEquals(1,emailLogs.size(),'Email Log not created as expected');
        System.assertEquals('Error',emailLogs[0].Status__c,'Email Log not create with the right status');
    }
}