objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Ending Date of Service for this opportunity</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Engagement_Type__c</fullName>
        <description>Engagement Type field is a dependent pick list of Status and will be required when an opportunity is Closed/Won. Fires off a workflow to notify certain individuals</description>
        <inlineHelpText>This will notify the specific department/group when a Opportunity has been closed won</inlineHelpText>
        <label>Engagement Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Projects</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
                <value>
                    <fullName>Workforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Engineering_Margin__c</fullName>
        <description>Manually input of the engineering margin in %</description>
        <label>Engineering Margin %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Engineering_Revenue__c</fullName>
        <description>Revenue relating to the engineering service component</description>
        <label>Engineering Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>New_Business_or_Renewal__c</fullName>
        <description>Is this opportunity new business or renewal</description>
        <label>New Business or Renewal</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Contact for this Project</description>
        <label>Project Lead</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <description>Reason for Closed Deal</description>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Value</fullName>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
                <value>
                    <fullName>Solution Quality</fullName>
                </value>
                <value>
                    <fullName>Unique Solution</fullName>
                </value>
                <value>
                    <fullName>No Client Action</fullName>
                </value>
                <value>
                    <fullName>Outsold</fullName>
                </value>
                <value>
                    <fullName>Better Solution</fullName>
                </value>
                <value>
                    <fullName>Client Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Client Lost</fullName>
                </value>
                <value>
                    <fullName>Best No Bid</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Customer Service Issue</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The date when the engagement is scheduled to commence</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Strategic_Or_Tactical__c</fullName>
        <description>Used for determining if the sale was strategical or tactical</description>
        <label>Strategic Or Tactical</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Strategic</fullName>
                </value>
                <value>
                    <fullName>Tactical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Revenue__c</fullName>
        <description>Manually inserted in and is the total revenuw generated from engineers and outsourced services</description>
        <label>Total Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VF_Closed_Won_Notification_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only check if sendPdfForClosedWonTrigger fires off notification for a record</description>
        <inlineHelpText>Hidden</inlineHelpText>
        <label>VF Closed Won Notification Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VF_Closed_Won__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggers off sendPdfForClosedWonTrigger trigger after update to send PDF to recipients</description>
        <label>VF Closed Won</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SendVFAsAttachmentTest.cls
@isTest  
public class SendVFAsAttachmentTest{	

    /* The following oppUpdateTrigger test sendPDfForClosedWondTrigger.apxt on update. 
	*  This also test @futures method by invoking SendVFAsAttachment.sendVF method however ignoring the http web service call
	*/
    public static testMethod void oppUpdateTrigger(){ 
        list<Opportunity> oppList = new List<Opportunity>();    
    	Account a = new Account(Name='Test Account');
        insert a;
        Contact c = new Contact(FirstName='Jake',LastName='Spears',AccountId=a.id);
        insert c;
        
        for(integer i=0;i<10;i++){
            Opportunity o = new Opportunity();
            o.Name = 'Opp Name ' + i;
            o.AccountId = a.Id;
            o.Amount = 10000;
            o.StageName = 'Proposal';
            o.CloseDate = System.today() + 5;
            oppList.add(o);
        }
        
        Opportunity newOp = new Opportunity(
            Name = 'Opp Name Additional',
            AccountId = a.Id,
            Amount = 10000,
            StageName = 'Proposal',
            CloseDate = System.today() + 5
            );
        
        insert newOp;
        insert oppList;        
              
        
        test.startTest();
		
        for(Opportunity o:oppList){
        	o.StageName = 'Closed Won';
            o.Reason__c = 'Value';
            o.Engagement_Type__c = 'Projects';
            o.Strategic_Or_Tactical__c = 'Tactical';
            o.Start_Date__c = System.today() + 10;
            o.End_Date__c = System.today() + 15;
            o.New_Business_or_Renewal__c = 'New Business';
            o.LeadSource = 'Call in';
            o.Engineering_Revenue__c = 200;
            o.Engineering_Margin__c = 50;
            o.Total_Revenue__c = 500;
            o.Project_Lead__c = c.Id;
            o.VF_Closed_Won__c = true;
            o.VF_Closed_Won_Notification_Sent__c = false;
        }
                                            
        update oppList;
        
        newOp.StageName = 'Closed Won';
        newOp.Reason__c = 'Value';
        newOp.Engagement_Type__c = 'Projects';
        newOp.Strategic_Or_Tactical__c = 'Tactical';
        newOp.Start_Date__c = System.today() + 10;
        newOp.End_Date__c = System.today() + 15;
        newOp.New_Business_or_Renewal__c = 'New Business';
        newOp.LeadSource = 'Call in';
        newOp.Engineering_Revenue__c = 200;
        newOp.Engineering_Margin__c = 50;
        newOp.Total_Revenue__c = 500;
        newOp.Project_Lead__c = c.Id;
        newOp.VF_Closed_Won__c = true;
        newOp.VF_Closed_Won_Notification_Sent__c = false;
        
        oppList.add(newOp);
        update oppList;
        
        SendVFAsAttachment.sendVF('joey_hoey19@hotmail.com','Sample Test from Trigger','Sample Email Body',oppList[0].id,UserInfo.getSessionId());          		
        
    }
	
 	/*  Rest API Test executed in this manner as follows
	*/     
    public static testMethod void testCallout() {
        // Set mock callout class 
        //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
             
        /*
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        HttpResponse res = CalloutClass.getInfoFromExternalService();
        
        // Verify response received contains fake values
        String contentType = res.getHeader('Content-Type');
        System.assert(contentType == 'application/json');
        String actualValue = res.getBody();
        String expectedValue = '{"foo":"bar"}';
        System.assertEquals(actualValue, expectedValue);
        System.assertEquals(200, res.getStatusCode());
		*/
        
        RestRequest request = new RestRequest(); 
        RestResponse response = new RestResponse();
        
        request.requestURI = URL.getSalesforceBaseUrl().toExternalForm() + '/services/apexrest/sendPDFEmail';  
        request.httpMethod = 'POST';
        
        RestContext.request = request;
        RestContext.response = response;
		GETPDFContent.sendEmail('joey@cloudycode.com.au', 'Subject', 'body', '');
    }
    
}