objects/ProductConsumed.object
<CustomObject>
    <fields>
        <fullName>Matching_Service_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Matching Service Part</label>
        <referenceTo>Service_Part__c</referenceTo>
        <relationshipLabel>Matching Products Consumed</relationshipLabel>
        <relationshipName>Matching_Products_Consumed</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request_Part__c.object
<CustomObject>
    <description>Record triggers process builder and flows to create new product request with line items.</description>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Name to be requested</description>
        <label>Product Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Requested Parts</relationshipLabel>
        <relationshipName>Requested_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Service this Part request is for</description>
        <label>Service</label>
        <referenceTo>CKSW_BASE__Service__c</referenceTo>
        <relationshipLabel>Requested Parts</relationshipLabel>
        <relationshipName>Requested_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request Part</label>
    <nameField>
        <displayFormat>RPN-{00000}</displayFormat>
        <label>Request Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Part__c.object
<CustomObject>
    <description>Custom object to allow global action on a Service automating insertion of Product Consumed or Products Required</description>
    <fields>
        <fullName>Product_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Item from Van Stock</description>
        <label>Product Item</label>
        <referenceTo>ProductItem</referenceTo>
        <relationshipLabel>Service_Parts</relationshipLabel>
        <relationshipName>Service_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <formula>Product_Item__r.Product2.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_Consumed__c</fullName>
        <label>Quantity Consumed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>CKSW_BASE__Service__c</referenceTo>
        <relationshipLabel>Service Parts</relationshipLabel>
        <relationshipName>Service_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Part</label>
    <nameField>
        <displayFormat>SPN-{000000}</displayFormat>
        <label>Service Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service_Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ProductConsumedTriggerController.cls
/*
*   Created by Joey Ho 21/07/2017
*/
public without sharing class ProductConsumedTriggerController {
    
    public static boolean flag_updateSerivceParts = false; //Used in ProductConsumedTrigger as well as ServicePartTrigger to avoid overwriting
    public static boolean flag_isDeletingProductOrServicePart = false;

    /*
    //Returns list Service Part that matches to the Product Consumed that was deleted
    public list<Service_Part__c> getFilteredServiceParts(list<ProductConsumed> oldList){
        list<Service_Part__c> sobjList = new list<Service_Part__c>();
        for(ProductConsumed pc : oldList){
            if(pc.Matching_Service_Part__c!=null)
                sobjList.add(new Service_Part__c(Id=pc.Matching_Service_Part__c));
        }    
        system.debug('delete --- '+ sobjList);
        return sobjList;
    }
	*/
    //Returns list of matching conusming parts given old map
    public list<ProductConsumed> getFilteredProductConsumedList(map<Id,Service_Part__c> oldMap){
        list<ProductConsumed> sobjList = new list<ProductConsumed>();  
        system.debug('---oldMap.keySet()--- ' + oldMap.keySet());
      

      for(ProductConsumed pc : [SELECT Id, Matching_Service_Part__c FROM ProductConsumed WHERE Matching_Service_Part__c IN: oldMap.keySet()]){
            sobjList.add(pc);
        }   

        system.debug('length --- '+ sobjList.size());
        system.debug('delete --- '+ sobjList);
        return sobjList;
    }
	
    /*
    //Updates Service Parts that have quantity changed from the Product Consumed record
    public void updateSerivceParts(map<Id,ProductConsumed> newMap, Map<Id,ProductConsumed> oldMap){
    	flag_updateSerivceParts = true;

        map<Id,Id> ServicePart2PcIds = new map<Id,Id>();

        for(Id key: newMap.keySet()){
            if(newMap.get(key).QuantityConsumed != oldMap.get(key).QuantityConsumed){
                ServicePart2PcIds.put(newMap.get(key).Matching_Service_Part__c,key);
            }
        }

        if(!ServicePart2PcIds.isEmpty()){
            list<Service_Part__c> spUpdate = new list<Service_Part__c>();
            for(Service_Part__c sp : [SELECT Id, Quantity_Consumed__c FROM Service_Part__c WHERE Id IN: ServicePart2PcIds.keySet()]){
                Id pcId = ServicePart2PcIds.get(sp.Id);
                sp.Quantity_Consumed__c = newMap.get(pcId).QuantityConsumed;
                spUpdate.add(sp);
            }

            update spUpdate;
        }
    }
	*/
    //For Technicians to update Product Consumed - Joey Ho - 25/07/2017
    public void updateSerivceParts(map<Id,Service_Part__c> newMap, Map<Id,Service_Part__c> oldMap){
        flag_updateSerivceParts = true;

        set<id> ServicePartSet = new set<id>();
        list<ProductConsumed> pc2Update = new list<ProductConsumed>();

        for(Id key : newMap.keySet()){
            if(newMap.get(key).Product_Item__c != oldMap.get(key).Product_Item__c)
                newMap.get(key).addError('You can not change the Product Item Consumed. Please Delete this item and create a new one.');

            if(newMap.get(key).Quantity_Consumed__c != oldMap.get(key).Quantity_Consumed__c)
                ServicePartSet.add(key);
        }

        for(ProductConsumed pc : [SELECT Id, QuantityConsumed, ProductItemId, Matching_Service_Part__c FROM ProductConsumed WHERE Matching_Service_Part__c IN: ServicePartSet]){
            Id spId = pc.Matching_Service_Part__c;
            pc.QuantityConsumed = newMap.get(spId).Quantity_Consumed__c;
            //pc.ProductItemId = newMap.get(spId).Product_Item__c;
            pc2Update.add(pc);
        }
        
        integer i = 0;
        Database.SaveResult[] srList = Database.update(pc2Update, false);
        for (Database.SaveResult sr : srList) {
            if (!sr.isSuccess()) {
                for(Database.Error err : sr.getErrors()){
                    Id key = pc2Update[i].Matching_Service_Part__c;
                    newMap.get(key).addError(' updating Service Part - '+err.getMessage());
                }
            }
            i++;
        }
    }   

    //Checks product items in Stock Van locations contain enough quantity before proceeding
    public void stockLocationcheck(list<Service_Part__c> newList){
        set<Id> serviceIds = new set<Id>();
        set<Id> prodItems = new set<Id>();
        for(Service_Part__c sp : newList){
            serviceIds.add(sp.Service__c);
            prodItems.add(sp.Product_Item__c);
        }

        set<Id> product2Ids = new set<Id>();        
        map<Id,decimal> vanStockMap = new map<id,decimal>();
        for(ProductItem pi:[SELECT id, Product2Id, QuantityOnHand FROM ProductItem WHERE Id IN:prodItems]){
            vanStockMap.put(pi.Id,pi.QuantityOnHand);
            product2Ids.add(pi.product2Id);
        }

/*
        //Get all request to check
        map<id,map<id,integer>> numOfReqMap = new map<id,map<id,integer>>();
        for(Request_Part__c rp:[SELECT id, Service__c FROM Request_Part__c WHERE Service__c IN:serviceIds AND product_Name__c IN: product2Ids]]){

        }
*/
        //Check if has van and part locations
        for(Service_Part__c sp:newList){
            if(!vanStockMap.containsKey(sp.Product_Item__c))
                sp.addError('You may not a Van or Stock to consume part');
            else{
                integer soh = integer.valueOf(vanStockMap.get(sp.Product_Item__c));
                if(soh==0)
                    sp.addError('You do not have any stock to consume for this product.');
                else if(sp.Quantity_Consumed__c > soh){
                    sp.addError('You only have '+soh+ ' stock on hand and cannot consume more than that.');
                }
            }
        }
    }

}