objects/Technician_Status_Transition__mdt.object
<CustomObject>
    <fields>
        <fullName>To_Status__c</fullName>
        <label>To Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Dispatched</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Travel Start</fullName>
                </value>
                <value>
                    <fullName>Travel End</fullName>
                </value>
                <value>
                    <fullName>Onsite</fullName>
                </value>
                <value>
                    <fullName>Capture Signature</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Technician Status Transition</label>
    <pluralLabel>Technician Status Transitions</pluralLabel>
</CustomObject>

classes/ChangeStatusControllerExtension.cls
public class ChangeStatusControllerExtension {
    
    public WorkOrder theWorkOrder;
    public List<String> nextStatusSelected {get; set;}
    public string woStatus {get; set;}
    
    public ApexPages.StandardController sc;

    public ChangeStatusControllerExtension(ApexPages.StandardController stdController){
        theWorkOrder = (WorkOrder)stdController.getRecord();
        nextStatusSelected = getNextStatusSelected(theWorkOrder.Status);
        this.sc = stdController;
    }

    public List<String> getNextStatusSelected(String fromStatus){
        List<Technician_Status_Transition__mdt> technicianStatusTransitions = CustomMetadataTypeDAO.getTechnStatusTransitionByFromStatusAPI(new String[]{fromStatus});
        List<String> options = new List<String>();
        for(Technician_Status_Transition__mdt statusTransition: technicianStatusTransitions){
            options.add(statusTransition.To_Status__c);
        }
        return options;
    }

    public PageReference updateWorkOrderStatus(){
        theWorkOrder.Status = woStatus;
        if(woStatus == Constants.WORK_ORDER_STATUS_CAPTURE_SIGNATURE){
            PageReference p = new PageReference(Url.getSalesforceBaseUrl().toExternalForm()+'/Technicians/apex/WOSignatureCapture?Id='+theWorkOrder.Id);
            return p;     
        }
        else{
            return sc.save();
        }
    }
}