objects/Usage_FSL__c.object
<CustomObject>
    <description>BEST TS Usage for Field Service Lightning</description>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>CKSW_BASE__Service__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Engineering_Cost__c</fullName>
        <label>Total Engineering Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Engineering_Revenue__c</fullName>
        <label>Total Engineering Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Pass_Through_Cost__c</fullName>
        <label>Total Pass Through Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Pass_Through_Revenue__c</fullName>
        <label>Total Pass Through Revenue</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <displayFormat>US-{0000000}</displayFormat>
        <label>Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UsageDAO.cls
public class UsageDAO {

    //public static List<Usage_FSL__c> getUsagesById(Set<Id> usageIds) {
    //    return [SELECT  Service__c FROM    Usage_FSL__c
    //             WHERE   Id IN : usageIds];
    //}

    //public static List<AggregateResult> getUsagesAggregateResult(Set<Id> usageIds) {
    //    return [SELECT  Service__c , 
    //                     SUM(Total_Engineering_Cost__c) totalenggcost, 
    //                     SUM(Total_Engineering_Revenue__c) totalenggrevenue, 
    //                     SUM(Total_Pass_Through_Cost__c) totalpassthrcost, 
    //                     SUM(Total_Pass_Through_Revenue__c) totalpassthrrevenue 
    //            FROM Usage_FSL__c
    //            WHERE Id IN : usageIds
    //            GROUP BY ROLLUP(Service__c)];
    //}

    //public static Map<Id, Usage_FSL__c> getUsageMap(List<Id> serviceIds, Set<Id> usageIds) {

    //    return new Map<Id, Usage_FSL__c>([SELECT Id  FROM Usage_FSL__c 
    //                                       WHERE Service__c IN : serviceIds AND 
    //                                             Id NOT IN: usageIds]);
    //}

    //public static Map<Id, Usage_FSL__c> getUsageMap(List<Id> serviceIds) {

    //    return new Map<Id, Usage_FSL__c>([SELECT Id FROM Usage_FSL__c 
    //                                      WHERE Service__c IN : serviceIds]);
    //}
    public static List<Usage_FSL__c> getUsagesById(Set<Id> usageIds) {
        return [SELECT Service_Work_Order__c 
                FROM   Usage_FSL__c
                WHERE  Id IN : usageIds];
    }

    public static List<AggregateResult> getUsagesAggregateResult(Set<Id> usageIds) {
        return [SELECT  Service_Work_Order__c , 
                         SUM(Total_Engineering_Cost__c) totalenggcost, 
                         SUM(Total_Engineering_Revenue__c) totalenggrevenue, 
                         SUM(Total_Pass_Through_Cost__c) totalpassthrcost, 
                         SUM(Total_Pass_Through_Revenue__c) totalpassthrrevenue 
                FROM Usage_FSL__c
                WHERE Id IN : usageIds
                GROUP BY ROLLUP(Service_Work_Order__c)];
    }

    public static Map<Id, Usage_FSL__c> getUsageMap(Set<Id> woServiceIds, Set<Id> usageIds) {

        return new Map<Id, Usage_FSL__c>([  SELECT Id,
                                                    Service_Work_Order__c
                                            FROM Usage_FSL__c 
                                            WHERE Service_Work_Order__c IN : woServiceIds AND 
                                                 Id NOT IN: usageIds]);
    }

    public static Map<Id, Usage_FSL__c> getUsageMap(Set<Id> woServiceIds) {

        return new Map<Id, Usage_FSL__c>([  SELECT  Id,
                                                    Service_Work_Order__c
                                            FROM Usage_FSL__c 
                                            WHERE Service_Work_Order__c IN : woServiceIds]);
    }
}